### ISSUE TITLE
Bundle.get_messages() append fragments in random order

### ISSUE THREAD

**Issue by wafflecomposite** [iotaledger/iota.lib.py#128] opened 2018-01-02 17:28 UTC
Hello and thanks you for this library.
I tried to implement some 'empty transactions' chat through tangle, and found Bundle.get_messages() function pretty useful for such task. But on large messages that are divided into several transactions, I found that this function gives corrupted data.
After some trials, I found that in this piece of function code
```
for txn in group:
        message_trytes += txn.signature_message_fragment
```
transations in 'group' list are pretty much unsorted, which doesn't really make much sense.
I believe that this should be fixed by changing aforecited 'for' line to something like
`for txn in sorted(group, key=lambda txn: txn.current_index):`
or by some Bundle.group_transactions() rewriting.
Thanks

**Comment by todofixthis** [comment] 2018-01-03 06:49
Hey @wafflecomposite thanks for reporting this issue!  Looks like there's a hole in our unit tests 😓 

I'll have a look later this week.

**Comment by todofixthis** [comment] 2018-01-06 03:03
Hey @wafflecomposite I'm looking into this issue now, but I'm having some difficulty reproducing it.

`group_transactions` should already be returning transactions sorted by `current_index`; the sorting happens in the [Bundle initalizer](https://github.com/iotaledger/iota.lib.py/blob/2.0.3/iota/transaction/base.py#L380-L384):

```python
self.transactions = [] # type: List[Transaction]
if transactions:
  self.transactions.extend(
    sorted(transactions, key=attrgetter('current_index'))
  )
```

Could you provide a bundle hash or some trytes that can reproduce the issue you're encountering?

**Comment by todofixthis** [comment] 2018-01-26 21:56
Hey @wafflecomposite I'm going to close this issue, as I'm unable to reproduce it.

If you are still encountering it, feel free to reopen this issue so I can keep investigating.  If you are able to nail down steps to reproduce the problem, that would be super helpful!

Cheers!

**Closed by todofixthis** 2018-01-26 21:56 UTC
Labels: bug
